/**
 * Built-in catalog snapshot derived from a reference spacehaven.jar
 *
 * This file is auto-generated by scripts/generate-jar-catalog.ts
 * DO NOT EDIT MANUALLY
 *
 * Source: spacehaven.jar
 * Size: 186209507 bytes
 * Game Version: 0.20.0_steam_29
 * Generated: 2026-01-10T02:28:47.387Z
 */

import type { StructureCatalog } from '@/data/types'
import type { JarSourceInfo } from './types'

/**
 * Metadata about the source JAR used to generate this snapshot
 */
export const BUILTIN_SOURCE_INFO: JarSourceInfo = {
  fileName: "spacehaven.jar",
  fileSize: 186209507,
  lastModified: 1768012127387,
  extractedAt: 1768012127387,
  gameVersion: "0.20.0_steam_29",
}

/**
 * The built-in catalog snapshot
 */
export const BUILTIN_CATALOG: StructureCatalog = {
  "categories": [
    {
      "id": "power",
      "name": "Power",
      "color": "#cc8844",
      "defaultLayer": "Systems",
      "items": [
        {
          "id": "mid_3489",
          "name": "Backup Power Node",
          "size": [
            2,
            2
          ],
          "color": "hsl(229, 47%, 36%)",
          "categoryId": "power"
        },
        {
          "id": "mid_2684",
          "name": "Energium Power Generator",
          "size": [
            2,
            1
          ],
          "color": "hsl(240, 40%, 45%)",
          "categoryId": "power"
        },
        {
          "id": "mid_3202",
          "name": "Large Power Node",
          "size": [
            2,
            2
          ],
          "color": "hsl(350, 56%, 45%)",
          "categoryId": "power"
        },
        {
          "id": "mid_3985",
          "name": "Platform",
          "size": [
            2,
            2
          ],
          "color": "hsl(29, 60%, 46%)",
          "categoryId": "power"
        },
        {
          "id": "mid_782",
          "name": "Pod Hangar",
          "size": [
            3,
            1
          ],
          "color": "hsl(186, 42%, 46%)",
          "categoryId": "power"
        },
        {
          "id": "mid_3204",
          "name": "Power Capacity Node",
          "size": [
            2,
            2
          ],
          "color": "hsl(285, 61%, 43%)",
          "categoryId": "power"
        },
        {
          "id": "mid_3501",
          "name": "Power Conduit",
          "size": [
            2,
            2
          ],
          "color": "hsl(59, 41%, 36%)",
          "categoryId": "power"
        },
        {
          "id": "mid_761",
          "name": "Shuttle Hangar",
          "size": [
            7,
            6
          ],
          "color": "hsl(30, 67%, 47%)",
          "categoryId": "power"
        },
        {
          "id": "mid_3269",
          "name": "Small Power Node",
          "size": [
            2,
            2
          ],
          "color": "hsl(98, 67%, 39%)",
          "categoryId": "power"
        },
        {
          "id": "mid_2101",
          "name": "Solar Panel",
          "size": [
            2,
            2
          ],
          "color": "hsl(109, 52%, 54%)",
          "categoryId": "power"
        },
        {
          "id": "mid_200",
          "name": "Space Suit Locker",
          "size": [
            1,
            1
          ],
          "color": "hsl(145, 59%, 36%)",
          "categoryId": "power"
        },
        {
          "id": "mid_120",
          "name": "X1 Airlock",
          "size": [
            7,
            3
          ],
          "color": "hsl(266, 61%, 43%)",
          "categoryId": "power"
        },
        {
          "id": "mid_708",
          "name": "X1 Power Generator",
          "size": [
            2,
            1
          ],
          "color": "hsl(223, 53%, 54%)",
          "categoryId": "power"
        },
        {
          "id": "mid_1530",
          "name": "X2 Power Generator",
          "size": [
            3,
            2
          ],
          "color": "hsl(110, 47%, 44%)",
          "categoryId": "power"
        },
        {
          "id": "mid_344",
          "name": "X3 Power Generator",
          "size": [
            4,
            2
          ],
          "color": "hsl(301, 69%, 36%)",
          "categoryId": "power"
        }
      ]
    },
    {
      "id": "life_support",
      "name": "Life Support",
      "color": "#44aa88",
      "defaultLayer": "Systems",
      "items": [
        {
          "id": "mid_72",
          "name": "Air Vent",
          "size": [
            1,
            1
          ],
          "color": "hsl(51, 46%, 37%)",
          "categoryId": "life_support"
        },
        {
          "id": "mid_922",
          "name": "Gas scrubber",
          "size": [
            1,
            1
          ],
          "color": "hsl(25, 65%, 48%)",
          "categoryId": "life_support"
        },
        {
          "id": "mid_47",
          "name": "Hull Window",
          "size": [
            1,
            3
          ],
          "color": "hsl(83, 42%, 51%)",
          "categoryId": "life_support"
        },
        {
          "id": "mid_2758",
          "name": "Hull Window",
          "size": [
            1,
            2
          ],
          "color": "hsl(83, 42%, 51%)",
          "categoryId": "life_support"
        },
        {
          "id": "mid_206",
          "name": "Hull Window",
          "size": [
            1,
            4
          ],
          "color": "hsl(83, 42%, 51%)",
          "categoryId": "life_support"
        },
        {
          "id": "mid_927",
          "name": "Oxygen Generator",
          "size": [
            2,
            1
          ],
          "color": "hsl(197, 50%, 48%)",
          "categoryId": "life_support"
        },
        {
          "id": "mid_993",
          "name": "Spacesuit door",
          "size": [
            3,
            1
          ],
          "color": "hsl(11, 44%, 46%)",
          "categoryId": "life_support"
        },
        {
          "id": "mid_1798",
          "name": "Station Hull Door",
          "size": [
            3,
            1
          ],
          "color": "hsl(195, 54%, 53%)",
          "categoryId": "life_support"
        },
        {
          "id": "mid_918",
          "name": "Thermal Regulator",
          "size": [
            2,
            2
          ],
          "color": "hsl(88, 52%, 38%)",
          "categoryId": "life_support"
        },
        {
          "id": "mid_987",
          "name": "Wall Thermal Regulator",
          "size": [
            1,
            1
          ],
          "color": "hsl(218, 49%, 39%)",
          "categoryId": "life_support"
        },
        {
          "id": "mid_2757",
          "name": "Wall Window",
          "size": [
            2,
            2
          ],
          "color": "hsl(158, 69%, 37%)",
          "categoryId": "life_support"
        },
        {
          "id": "mid_25",
          "name": "X1 Door",
          "size": [
            1,
            1
          ],
          "color": "hsl(45, 42%, 54%)",
          "categoryId": "life_support"
        },
        {
          "id": "mid_44",
          "name": "X1 Wall",
          "size": [
            2,
            2
          ],
          "color": "hsl(281, 44%, 46%)",
          "categoryId": "life_support"
        },
        {
          "id": "mid_2755",
          "name": "X2 Door",
          "size": [
            1,
            2
          ],
          "color": "hsl(196, 49%, 37%)",
          "categoryId": "life_support"
        }
      ]
    },
    {
      "id": "system",
      "name": "Systems & Combat",
      "color": "#cc4444",
      "defaultLayer": "Systems",
      "items": [
        {
          "id": "mid_2783",
          "name": "Autoturret",
          "size": [
            2,
            2
          ],
          "color": "hsl(55, 53%, 43%)",
          "categoryId": "system"
        },
        {
          "id": "mid_4262",
          "name": "Cover Object",
          "size": [
            2,
            2
          ],
          "color": "hsl(176, 58%, 51%)",
          "categoryId": "system"
        },
        {
          "id": "mid_2242",
          "name": "Energy Turret",
          "size": [
            1,
            1
          ],
          "color": "hsl(144, 47%, 43%)",
          "categoryId": "system"
        },
        {
          "id": "mid_2257",
          "name": "Hull Stabilizer",
          "size": [
            2,
            1
          ],
          "color": "hsl(270, 58%, 47%)",
          "categoryId": "system"
        },
        {
          "id": "mid_2655",
          "name": "Hyperium Hyperdrive",
          "size": [
            6,
            12
          ],
          "color": "hsl(281, 58%, 41%)",
          "categoryId": "system"
        },
        {
          "id": "mid_3521",
          "name": "Hypersleep Chamber",
          "size": [
            2,
            2
          ],
          "color": "hsl(287, 54%, 53%)",
          "categoryId": "system"
        },
        {
          "id": "mid_263",
          "name": "Navigation console",
          "size": [
            1,
            1
          ],
          "color": "hsl(21, 47%, 35%)",
          "categoryId": "system"
        },
        {
          "id": "mid_2131",
          "name": "Operations console",
          "size": [
            1,
            1
          ],
          "color": "hsl(83, 55%, 50%)",
          "categoryId": "system"
        },
        {
          "id": "mid_3638",
          "name": "Point Defense Turret",
          "size": [
            2,
            2
          ],
          "color": "hsl(272, 51%, 38%)",
          "categoryId": "system"
        },
        {
          "id": "mid_2708",
          "name": "Rocket Turret",
          "size": [
            1,
            1
          ],
          "color": "hsl(316, 63%, 50%)",
          "categoryId": "system"
        },
        {
          "id": "mid_4215",
          "name": "Scanner",
          "size": [
            2,
            2
          ],
          "color": "hsl(262, 61%, 52%)",
          "categoryId": "system"
        },
        {
          "id": "mid_470",
          "name": "Shield Generator",
          "size": [
            1,
            1
          ],
          "color": "hsl(332, 52%, 42%)",
          "categoryId": "system"
        },
        {
          "id": "mid_2127",
          "name": "Shields console",
          "size": [
            1,
            1
          ],
          "color": "hsl(55, 55%, 36%)",
          "categoryId": "system"
        },
        {
          "id": "mid_3264",
          "name": "Small Shield Generator",
          "size": [
            2,
            2
          ],
          "color": "hsl(245, 40%, 35%)",
          "categoryId": "system"
        },
        {
          "id": "mid_4231",
          "name": "Solar Panel",
          "size": [
            2,
            2
          ],
          "color": "hsl(109, 52%, 54%)",
          "categoryId": "system"
        },
        {
          "id": "mid_2724",
          "name": "Targeting Jammer",
          "size": [
            1,
            1
          ],
          "color": "hsl(197, 68%, 53%)",
          "categoryId": "system"
        },
        {
          "id": "mid_2125",
          "name": "Weapons console",
          "size": [
            1,
            1
          ],
          "color": "hsl(230, 65%, 38%)",
          "categoryId": "system"
        },
        {
          "id": "mid_2123",
          "name": "X1 Hyperdrive",
          "size": [
            8,
            12
          ],
          "color": "hsl(13, 54%, 54%)",
          "categoryId": "system"
        },
        {
          "id": "mid_3510",
          "name": "X1 System Core",
          "size": [
            1,
            2
          ],
          "color": "hsl(295, 50%, 44%)",
          "categoryId": "system"
        },
        {
          "id": "mid_43",
          "name": "X1 Wall",
          "size": [
            2,
            2
          ],
          "color": "hsl(281, 44%, 46%)",
          "categoryId": "system"
        },
        {
          "id": "mid_3515",
          "name": "X2 System Core",
          "size": [
            1,
            3
          ],
          "color": "hsl(194, 64%, 47%)",
          "categoryId": "system"
        },
        {
          "id": "mid_3516",
          "name": "X3 System Core",
          "size": [
            1,
            4
          ],
          "color": "hsl(189, 49%, 50%)",
          "categoryId": "system"
        }
      ]
    },
    {
      "id": "storage",
      "name": "Storage",
      "color": "#888866",
      "defaultLayer": "Rooms",
      "items": [
        {
          "id": "mid_3561",
          "name": "Asteroid Cargo Port",
          "size": [
            1,
            4
          ],
          "color": "hsl(150, 65%, 41%)",
          "categoryId": "storage"
        },
        {
          "id": "mid_3062",
          "name": "Body Storage",
          "size": [
            2,
            1
          ],
          "color": "hsl(117, 57%, 42%)",
          "categoryId": "storage"
        },
        {
          "id": "mid_3543",
          "name": "Cargo Port",
          "size": [
            8,
            7
          ],
          "color": "hsl(179, 42%, 40%)",
          "categoryId": "storage"
        },
        {
          "id": "mid_632",
          "name": "Large Storage",
          "size": [
            3,
            1
          ],
          "color": "hsl(134, 68%, 44%)",
          "categoryId": "storage"
        },
        {
          "id": "mid_3068",
          "name": "Robot Storage",
          "size": [
            2,
            1
          ],
          "color": "hsl(333, 52%, 43%)",
          "categoryId": "storage"
        },
        {
          "id": "mid_82",
          "name": "Small Storage",
          "size": [
            1,
            1
          ],
          "color": "hsl(226, 44%, 52%)",
          "categoryId": "storage"
        },
        {
          "id": "mid_4068",
          "name": "Smuggler Storage",
          "size": [
            1,
            1
          ],
          "color": "hsl(103, 47%, 37%)",
          "categoryId": "storage"
        }
      ]
    },
    {
      "id": "food",
      "name": "Food & Agriculture",
      "color": "#66aa44",
      "defaultLayer": "Rooms",
      "items": [
        {
          "id": "mid_2704",
          "name": "Alcohol Beverage Machine",
          "size": [
            2,
            1
          ],
          "color": "hsl(24, 46%, 36%)",
          "categoryId": "food"
        },
        {
          "id": "mid_2646",
          "name": "Algae Dispenser",
          "size": [
            2,
            1
          ],
          "color": "hsl(259, 65%, 49%)",
          "categoryId": "food"
        },
        {
          "id": "mid_982",
          "name": "Autopsy Table",
          "size": [
            3,
            2
          ],
          "color": "hsl(29, 64%, 43%)",
          "categoryId": "food"
        },
        {
          "id": "mid_1871",
          "name": "CO2 Producer",
          "size": [
            1,
            1
          ],
          "color": "hsl(148, 69%, 46%)",
          "categoryId": "food"
        },
        {
          "id": "mid_185",
          "name": "Grow Bed with Light",
          "size": [
            3,
            1
          ],
          "color": "hsl(96, 57%, 50%)",
          "categoryId": "food"
        },
        {
          "id": "mid_184",
          "name": "Grow Bed with Light",
          "size": [
            2,
            1
          ],
          "color": "hsl(96, 57%, 50%)",
          "categoryId": "food"
        },
        {
          "id": "mid_921",
          "name": "Grow Bed with Light",
          "size": [
            4,
            1
          ],
          "color": "hsl(96, 57%, 50%)",
          "categoryId": "food"
        },
        {
          "id": "mid_623",
          "name": "Kitchen",
          "size": [
            3,
            1
          ],
          "color": "hsl(4, 47%, 36%)",
          "categoryId": "food"
        }
      ]
    },
    {
      "id": "resource",
      "name": "Resource & Industry",
      "color": "#aa8844",
      "defaultLayer": "Rooms",
      "items": [
        {
          "id": "mid_2002",
          "name": "Advanced Assembler",
          "size": [
            3,
            1
          ],
          "color": "hsl(34, 66%, 49%)",
          "categoryId": "resource"
        },
        {
          "id": "mid_1908",
          "name": "Assembler",
          "size": [
            3,
            1
          ],
          "color": "hsl(24, 60%, 36%)",
          "categoryId": "resource"
        },
        {
          "id": "mid_938",
          "name": "Chemical Refinery",
          "size": [
            3,
            1
          ],
          "color": "hsl(278, 49%, 35%)",
          "categoryId": "resource"
        },
        {
          "id": "mid_2458",
          "name": "Composter",
          "size": [
            2,
            1
          ],
          "color": "hsl(274, 69%, 54%)",
          "categoryId": "resource"
        },
        {
          "id": "mid_979",
          "name": "Energy Refinery",
          "size": [
            3,
            1
          ],
          "color": "hsl(156, 42%, 39%)",
          "categoryId": "resource"
        },
        {
          "id": "mid_125",
          "name": "Item Fabricator",
          "size": [
            2,
            1
          ],
          "color": "hsl(64, 40%, 37%)",
          "categoryId": "resource"
        },
        {
          "id": "mid_3615",
          "name": "Item Workbench",
          "size": [
            2,
            1
          ],
          "color": "hsl(110, 64%, 38%)",
          "categoryId": "resource"
        },
        {
          "id": "mid_947",
          "name": "Metal Refinery",
          "size": [
            4,
            1
          ],
          "color": "hsl(67, 56%, 49%)",
          "categoryId": "resource"
        },
        {
          "id": "mid_1964",
          "name": "Micro-Weaver",
          "size": [
            3,
            1
          ],
          "color": "hsl(87, 44%, 46%)",
          "categoryId": "resource"
        },
        {
          "id": "mid_1989",
          "name": "Optronics Fabricator",
          "size": [
            4,
            1
          ],
          "color": "hsl(32, 47%, 40%)",
          "categoryId": "resource"
        },
        {
          "id": "mid_3520",
          "name": "Ore Processor",
          "size": [
            3,
            1
          ],
          "color": "hsl(340, 44%, 47%)",
          "categoryId": "resource"
        },
        {
          "id": "mid_1880",
          "name": "Recycler",
          "size": [
            3,
            1
          ],
          "color": "hsl(217, 52%, 50%)",
          "categoryId": "resource"
        },
        {
          "id": "mid_1447",
          "name": "Tools Facility",
          "size": [
            2,
            1
          ],
          "color": "hsl(32, 53%, 43%)",
          "categoryId": "resource"
        },
        {
          "id": "mid_2451",
          "name": "Water Collector",
          "size": [
            1,
            1
          ],
          "color": "hsl(300, 52%, 44%)",
          "categoryId": "resource"
        },
        {
          "id": "mid_2010",
          "name": "Water Purifier",
          "size": [
            2,
            1
          ],
          "color": "hsl(165, 52%, 54%)",
          "categoryId": "resource"
        }
      ]
    },
    {
      "id": "facility",
      "name": "Crew Facilities",
      "color": "#6688aa",
      "defaultLayer": "Rooms",
      "items": [
        {
          "id": "mid_4114",
          "name": "Advanced Learning System",
          "size": [
            1,
            1
          ],
          "color": "hsl(147, 41%, 48%)",
          "categoryId": "facility"
        },
        {
          "id": "mid_3870",
          "name": "Advanced Medical Bed",
          "size": [
            1,
            2
          ],
          "color": "hsl(124, 49%, 45%)",
          "categoryId": "facility"
        },
        {
          "id": "mid_1606",
          "name": "Arcade Machine",
          "size": [
            1,
            1
          ],
          "color": "hsl(247, 51%, 54%)",
          "categoryId": "facility"
        },
        {
          "id": "mid_2804",
          "name": "Enslavement Facility",
          "size": [
            1,
            2
          ],
          "color": "hsl(79, 61%, 37%)",
          "categoryId": "facility"
        },
        {
          "id": "mid_1647",
          "name": "Hypersleep Chamber",
          "size": [
            1,
            1
          ],
          "color": "hsl(287, 54%, 53%)",
          "categoryId": "facility"
        },
        {
          "id": "mid_1526",
          "name": "Jukebox",
          "size": [
            1,
            1
          ],
          "color": "hsl(142, 61%, 50%)",
          "categoryId": "facility"
        },
        {
          "id": "mid_3878",
          "name": "Learning Computer",
          "size": [
            1,
            1
          ],
          "color": "hsl(53, 59%, 53%)",
          "categoryId": "facility"
        },
        {
          "id": "mid_76",
          "name": "Medical Bed",
          "size": [
            1,
            1
          ],
          "color": "hsl(30, 60%, 37%)",
          "categoryId": "facility"
        },
        {
          "id": "mid_3923",
          "name": "Medical Cabinet",
          "size": [
            1,
            1
          ],
          "color": "hsl(191, 53%, 49%)",
          "categoryId": "facility"
        },
        {
          "id": "mid_3880",
          "name": "Personal Entertainment",
          "size": [
            1,
            1
          ],
          "color": "hsl(72, 49%, 47%)",
          "categoryId": "facility"
        },
        {
          "id": "mid_1542",
          "name": "Research Lab",
          "size": [
            3,
            1
          ],
          "color": "hsl(312, 59%, 51%)",
          "categoryId": "facility"
        },
        {
          "id": "mid_3075",
          "name": "Research Workbench",
          "size": [
            2,
            1
          ],
          "color": "hsl(70, 61%, 43%)",
          "categoryId": "facility"
        },
        {
          "id": "mid_3406",
          "name": "Surgical Enhancement Facility",
          "size": [
            1,
            2
          ],
          "color": "hsl(123, 59%, 43%)",
          "categoryId": "facility"
        },
        {
          "id": "mid_123",
          "name": "X1 Toilet",
          "size": [
            2,
            1
          ],
          "color": "hsl(324, 69%, 38%)",
          "categoryId": "facility"
        },
        {
          "id": "mid_3719",
          "name": "X2 Hypersleep Tank",
          "size": [
            1,
            1
          ],
          "color": "hsl(95, 46%, 54%)",
          "categoryId": "facility"
        }
      ]
    },
    {
      "id": "robots",
      "name": "Robots",
      "color": "#55aaaa",
      "defaultLayer": "Systems",
      "items": [
        {
          "id": "mid_2882",
          "name": "Logistics Robot Station",
          "size": [
            1,
            2
          ],
          "color": "hsl(255, 53%, 51%)",
          "categoryId": "robots"
        },
        {
          "id": "mid_3055",
          "name": "Robot Workbench",
          "size": [
            2,
            1
          ],
          "color": "hsl(265, 51%, 37%)",
          "categoryId": "robots"
        },
        {
          "id": "mid_2891",
          "name": "Salvage Robot Station",
          "size": [
            1,
            2
          ],
          "color": "hsl(309, 44%, 35%)",
          "categoryId": "robots"
        }
      ]
    },
    {
      "id": "furniture",
      "name": "Furniture & Decoration",
      "color": "#aa8877",
      "defaultLayer": "Furniture",
      "items": [
        {
          "id": "mid_51",
          "name": "Bed",
          "size": [
            2,
            2
          ],
          "color": "hsl(57, 60%, 36%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_3362",
          "name": "Bedside Table",
          "size": [
            2,
            2
          ],
          "color": "hsl(2, 44%, 53%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_1864",
          "name": "Bunk Bed",
          "size": [
            2,
            2
          ],
          "color": "hsl(177, 41%, 40%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_3179",
          "name": "Cover Object",
          "size": [
            2,
            2
          ],
          "color": "hsl(176, 58%, 51%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_3953",
          "name": "Decorative Holy Cow",
          "size": [
            2,
            2
          ],
          "color": "hsl(241, 44%, 52%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_305",
          "name": "Decorative Object",
          "size": [
            2,
            2
          ],
          "color": "hsl(89, 59%, 54%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_3356",
          "name": "Decorative Plant",
          "size": [
            2,
            2
          ],
          "color": "hsl(123, 65%, 36%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_3373",
          "name": "Decorative Screen",
          "size": [
            1,
            1
          ],
          "color": "hsl(20, 69%, 39%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_3363",
          "name": "Green Wall",
          "size": [
            1,
            1
          ],
          "color": "hsl(241, 63%, 51%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_3131",
          "name": "In-floor Light",
          "size": [
            2,
            2
          ],
          "color": "hsl(182, 41%, 35%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_906",
          "name": "Light",
          "size": [
            2,
            2
          ],
          "color": "hsl(294, 58%, 35%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_295",
          "name": "Table",
          "size": [
            1,
            1
          ],
          "color": "hsl(158, 69%, 44%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_164",
          "name": "Wall Light",
          "size": [
            1,
            1
          ],
          "color": "hsl(344, 43%, 37%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_90",
          "name": "X1 Chair",
          "size": [
            2,
            2
          ],
          "color": "hsl(234, 54%, 39%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_307",
          "name": "X1 Couch",
          "size": [
            2,
            2
          ],
          "color": "hsl(193, 43%, 43%)",
          "categoryId": "furniture"
        },
        {
          "id": "mid_322",
          "name": "X1 Table",
          "size": [
            1,
            1
          ],
          "color": "hsl(113, 61%, 36%)",
          "categoryId": "furniture"
        }
      ]
    },
    {
      "id": "other",
      "name": "Other",
      "color": "#888888",
      "defaultLayer": "Rooms",
      "items": [
        {
          "id": "mid_2720",
          "name": "Asteroid power node",
          "size": [
            2,
            2
          ],
          "color": "hsl(134, 66%, 49%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3374",
          "name": "Backer Beer Machine",
          "size": [
            2,
            1
          ],
          "color": "hsl(197, 45%, 48%)",
          "categoryId": "other"
        },
        {
          "id": "mid_1968",
          "name": "Cell Fuser",
          "size": [
            3,
            1
          ],
          "color": "hsl(299, 60%, 47%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3182",
          "name": "Cover Object",
          "size": [
            2,
            2
          ],
          "color": "hsl(176, 58%, 51%)",
          "categoryId": "other"
        },
        {
          "id": "mid_1980",
          "name": "Electronic Fabricator",
          "size": [
            4,
            1
          ],
          "color": "hsl(217, 41%, 53%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3689",
          "name": "Evolving Alien Core",
          "size": [
            2,
            2
          ],
          "color": "hsl(358, 64%, 39%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3847",
          "name": "Green Wall",
          "size": [
            1,
            1
          ],
          "color": "hsl(241, 63%, 51%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3943",
          "name": "Holy Cow Monument",
          "size": [
            2,
            2
          ],
          "color": "hsl(320, 54%, 48%)",
          "categoryId": "other"
        },
        {
          "id": "mid_2763",
          "name": "Hull Window",
          "size": [
            1,
            2
          ],
          "color": "hsl(83, 42%, 51%)",
          "categoryId": "other"
        },
        {
          "id": "mid_2762",
          "name": "Hull Window",
          "size": [
            1,
            3
          ],
          "color": "hsl(83, 42%, 51%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3029",
          "name": "Hull Window",
          "size": [
            1,
            4
          ],
          "color": "hsl(83, 42%, 51%)",
          "categoryId": "other"
        },
        {
          "id": "mid_4377",
          "name": "In-floor Light",
          "size": [
            2,
            2
          ],
          "color": "hsl(182, 41%, 35%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3200",
          "name": "In-floor Power Node",
          "size": [
            2,
            2
          ],
          "color": "hsl(217, 58%, 52%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3622",
          "name": "Item Workbench",
          "size": [
            2,
            1
          ],
          "color": "hsl(110, 64%, 38%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3201",
          "name": "Large Power Node",
          "size": [
            2,
            2
          ],
          "color": "hsl(350, 56%, 45%)",
          "categoryId": "other"
        },
        {
          "id": "mid_4366",
          "name": "Large Storage",
          "size": [
            3,
            1
          ],
          "color": "hsl(134, 68%, 44%)",
          "categoryId": "other"
        },
        {
          "id": "mid_4373",
          "name": "Light",
          "size": [
            2,
            2
          ],
          "color": "hsl(294, 58%, 35%)",
          "categoryId": "other"
        },
        {
          "id": "mid_2483",
          "name": "Micro Breach",
          "size": [
            2,
            2
          ],
          "color": "hsl(299, 43%, 36%)",
          "categoryId": "other"
        },
        {
          "id": "mid_4322",
          "name": "Old Hyperdrive Remains",
          "size": [
            5,
            8
          ],
          "color": "hsl(142, 44%, 43%)",
          "categoryId": "other"
        },
        {
          "id": "mid_929",
          "name": "Platform",
          "size": [
            5,
            7
          ],
          "color": "hsl(29, 60%, 46%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3724",
          "name": "Pod Hangar",
          "size": [
            5,
            5
          ],
          "color": "hsl(186, 42%, 46%)",
          "categoryId": "other"
        },
        {
          "id": "mid_4306",
          "name": "Point Defense Turret",
          "size": [
            4,
            1
          ],
          "color": "hsl(272, 51%, 38%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3203",
          "name": "Power Capacity Node",
          "size": [
            2,
            2
          ],
          "color": "hsl(285, 61%, 43%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3673",
          "name": "Preservation Tank",
          "size": [
            2,
            2
          ],
          "color": "hsl(78, 69%, 42%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3667",
          "name": "Rogue Bot Charging Structure",
          "size": [
            2,
            2
          ],
          "color": "hsl(37, 64%, 54%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3732",
          "name": "Rogue Bot Drone Bay",
          "size": [
            3,
            1
          ],
          "color": "hsl(195, 55%, 38%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3723",
          "name": "Rogue Bot Fabricator",
          "size": [
            1,
            2
          ],
          "color": "hsl(242, 64%, 53%)",
          "categoryId": "other"
        },
        {
          "id": "mid_4240",
          "name": "Scanner",
          "size": [
            5,
            1
          ],
          "color": "hsl(262, 61%, 52%)",
          "categoryId": "other"
        },
        {
          "id": "mid_3199",
          "name": "Small Power Node",
          "size": [
            1,
            1
          ],
          "color": "hsl(98, 67%, 39%)",
          "categoryId": "other"
        },
        {
          "id": "mid_4365",
          "name": "Small Storage",
          "size": [
            2,
            2
          ],
          "color": "hsl(226, 44%, 52%)",
          "categoryId": "other"
        },
        {
          "id": "mid_4245",
          "name": "Solar Panel",
          "size": [
            2,
            2
          ],
          "color": "hsl(109, 52%, 54%)",
          "categoryId": "other"
        },
        {
          "id": "mid_4375",
          "name": "Wall Light",
          "size": [
            1,
            1
          ],
          "color": "hsl(344, 43%, 37%)",
          "categoryId": "other"
        },
        {
          "id": "mid_851",
          "name": "X1 Hyperdrive",
          "size": [
            8,
            12
          ],
          "color": "hsl(13, 54%, 54%)",
          "categoryId": "other"
        },
        {
          "id": "mid_4354",
          "name": "X1 Table",
          "size": [
            4,
            1
          ],
          "color": "hsl(113, 61%, 36%)",
          "categoryId": "other"
        }
      ]
    }
  ]
}

/**
 * Game version of the reference JAR
 */
export const BUILTIN_GAME_VERSION: string | null = "0.20.0_steam_29"

/**
 * Timestamp when the snapshot was generated
 */
export const BUILTIN_GENERATED_AT: number = 1768012127387

/**
 * Get the built-in catalog
 */
export function getBuiltinCatalog(): StructureCatalog {
  return BUILTIN_CATALOG
}

/**
 * Check if we're using a real JAR-derived snapshot vs static fallback
 */
export function hasRealJarSnapshot(): boolean {
  return true
}
